### ISSUE TITLE
SetTryDespawnOnConditionsInvalid = True not working anymore

### ISSUE THREAD

**Issue by jpee85** [ASharpPen/Valheim.SpawnThat#193]
Hey there,

some releases ago, I did override the leech spawn from the base game as follows to let them despawn on night to keep the existing number of leeches (and fps drops because leeches in water) low. When testing it was like 5-10 leeches spawned and in night the number dropped to zero. All worked fine. But the despawn at night, seems not to work anymore.

Example:

[WorldSpawner.39]
Name=
Enabled=True
Biomes=Swamp,
PrefabName=Leech
HuntPlayer=False
**MaxSpawned=5**
SpawnInterval=200
SpawnChance=50
LevelMin=1
LevelMax=3
LevelUpChance=-1
LevelUpMinCenterDistance=0
SpawnDistance=5
SpawnRadiusMin=0
SpawnRadiusMax=0
RequiredGlobalKey=
RequiredEnvironments=
GroupSizeMin=1
GroupSizeMax=1
GroupRadius=2
GroundOffset=0.5
SpawnDuringDay=True
**SpawnDuringNight=False**
ConditionAltitudeMin=-3
ConditionAltitudeMax=-0.1
ConditionTiltMin=0
ConditionTiltMax=35
SpawnInForest=True
SpawnOutsideForest=True
OceanDepthMin=0
OceanDepthMax=0
BiomeArea=-1
SetFaction=Undead
**SetTryDespawnOnConditionsInvalid = True**

Regards
JPee

**Comment by ASharpPen** [comment]
Seems to be working fine. I just tested it and things despawned as expected. 
Running this to test and just using the skiptime console command to quickly switch between night and day:
```INI
[WorldSpawner.0]
MaxSpawned=50
PrefabName=Boar
SpawnInterval=1
SpawnRadiusMin=1
SpawnRadiusMax=20
HuntPlayer=true
SpawnChance=100
GroupSizeMin=5
GroupSizeMax=5
GroupRadius=5
GroundOffset=100
SpawnInForest=True
SpawnOutsideForest=True
SpawnDuringDay=True
SpawnDuringNight=False
SetTryDespawnOnConditionsInvalid = True
```

Might be something else that is causing issues for you, logs might show errors or something else going on.

If you wanna verify that Spawn That is actually attempting to set the AI to despawn state, its possible if you have additional logging enabled. 
For that you need to enable 
- All `LogLevels` in `BepInEx.cfg` 
- Toggle `TraceLoggingOn` and `DebugLoggingOn` in `spawn_that.cfg`.

When that is enabled, you should see a message in your `LogOutput.log` file (or in the console for that matter) that says something like this:
`[Debug  :Spawn That!] Setting Boar(Clone) to despawn, due to daytime conditions.`

Note that you will need to restart your game for all the logging changes to take effect (bepinex.cfg requirement, Spawn That reloads on entering world).

**Comment by jpee85** [comment]
Thanks for the answer,

I've tested the same example for the boars, which is working for me. 

- Next I just switched prefab to Deer instead of Boar which did not work for me.
- Next I tried increasing the id to WorldSpawner.100001, which did not fix it for deer
- Next I tryed changing spawn during day to false and spawn during night to true, which dit not fix it for deer
- Also tryed boars and deers in parallel, boars escaped, deers didn't despawn

I am currently one minor version behind for our server, I will repeat the test with the newest. But it seems Deers do behave different than boars. In the log there was no output, no error. Only for boars i got the message for the despawn.

**Comment by jpee85** [comment]
I've also tested with the newest version, same result. Somehow what works for Boar does not work for Deer:

[WorldSpawner.0]
MaxSpawned=50
PrefabName=Deer
SpawnInterval=1
SpawnRadiusMin=1
SpawnRadiusMax=20
HuntPlayer=false
SpawnChance=100
GroupSizeMin=5
GroupSizeMax=5
GroupRadius=5
GroundOffset=100
SpawnInForest=True
SpawnOutsideForest=True
SpawnDuringDay=True
SpawnDuringNight=False
SetTryDespawnOnConditionsInvalid = True

Regards
JPee

**Comment by ASharpPen** [comment]
That makes sense for the Deer. You've stumbled upon an undocumented aspect of the despawning conditions. Most mobs in Valheim work off the "MonsterAI" component, but a few ones are based around a passive AI control. Deer is one of those.

These despawn features only work as you would expect for MonsterAI, as the others simply don't have the same functions available.

**Comment by jpee85** [comment]
Thanks for clarification.
