### ISSUE TITLE
Documentation for how World Spawner's "MaxSpawned" property works?

### ISSUE THREAD

**Issue by crwitt** [ASharpPen/Valheim.SpawnThat#8]
From the example config:

```
## Maximum entities spawned from this spawner type (it's complicated. See documentation.).
# Setting type: Int32
MaxSpawned = 4
```
Where can I find the documentation that you are referring to?

**Comment by ASharpPen** [comment]
Well spotted. I had planned to clarify on that one but apparently missed it.

What the parameter in the game "tries" to do, is to set a limit to how many cases of the prefab that there can be in the area.

To give you a short answer of why its weird, its because the game code checks for the "max spawn" in a rather complicated way. And I have yet to fully understand what the hell it's doing, since it seem to be either overcomplicating the issue, or be bugged, or just very inefficient.

**Comment by crwitt** [comment]
Ah, okay I understand. I was already itching to grab dnSpy and take a peek at the code so now might be good time.
Thanks for the answer and the great mod. I'm having a blast with it.
